# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 16:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('host', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(max_length=50)),
                ('source_latitude', models.FloatField()),
                ('source_longitude', models.FloatField()),
                ('destination', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_latitude', models.FloatField(blank=True, null=True)),
                ('destination_longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=5)),
                ('sdate', models.DateTimeField()),
                ('edate', models.DateTimeField(blank=True, null=True)),
                ('cdate', models.DateTimeField(default=datetime.datetime(2016, 11, 5, 1, 16, 17, 787964))),
            ],
            options={
                'db_table': 'demo_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
    ]
