# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_id', models.IntegerField(max_length=50)),
                ('writer', models.CharField(max_length=50)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('cdate', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'comment',
            },
        ),
    ]
